name: matbakhna_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-323.0.dev <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  firebase_database: ^11.3.5
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/imges12.jpg
