name: matbakhna_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-323.0.dev <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cake.jpg
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/imgas3.jpg
    - assets/images/logo.png
