// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClid_g69CTqzVPagnDHlnraqG7g-46_cM',
    appId: '1:246371733302:web:1fe9ae5064107e4481ed97',
    messagingSenderId: '246371733302',
    projectId: 'matbakhna-mobile',
    authDomain: 'matbakhna-mobile.firebaseapp.com',
    storageBucket: 'matbakhna-mobile.firebasestorage.app',
    measurementId: 'G-1DBY74RGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Vvg3cafrT6ACcLKnXvz16wHhoV4Pwxk',
    appId: '1:246371733302:android:2e707e232aa4f0b581ed97',
    messagingSenderId: '246371733302',
    projectId: 'matbakhna-mobile',
    storageBucket: 'matbakhna-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DppiLh2G10ChWonOnvEswVfJVh0J4Rk',
    appId: '1:246371733302:ios:5937670c5fd32a3d81ed97',
    messagingSenderId: '246371733302',
    projectId: 'matbakhna-mobile',
    storageBucket: 'matbakhna-mobile.firebasestorage.app',
    iosBundleId: 'com.example.matbakhnaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DppiLh2G10ChWonOnvEswVfJVh0J4Rk',
    appId: '1:246371733302:ios:5937670c5fd32a3d81ed97',
    messagingSenderId: '246371733302',
    projectId: 'matbakhna-mobile',
    storageBucket: 'matbakhna-mobile.firebasestorage.app',
    iosBundleId: 'com.example.matbakhnaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClid_g69CTqzVPagnDHlnraqG7g-46_cM',
    appId: '1:246371733302:web:254533cfbde5b52481ed97',
    messagingSenderId: '246371733302',
    projectId: 'matbakhna-mobile',
    authDomain: 'matbakhna-mobile.firebaseapp.com',
    storageBucket: 'matbakhna-mobile.firebasestorage.app',
    measurementId: 'G-3XDZMJQGZF',
  );
}
